### ISSUE TITLE
People picker: whitespace initiates search

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1486]
1. Click add persons
2. Add a single whitespace or multiple

**Expected results**
No results are returned

**Actual results**
All results are returned

<img width="386" alt="screen shot 2017-01-16 at 21 30 03" src="https://cloud.githubusercontent.com/assets/13200338/21999621/f6d16b0c-dc32-11e6-9b26-ec381194cd3d.png">

**Comment by hashraf88** [comment]
Also reported in Activiti https://github.com/Alfresco/activiti-bpm-suite/issues/3376

**Comment by VitoAlbano** [comment]
solved with #1484

**Comment by jdosti** [comment]
Tested on latest of development and can still reproduce. Tested on Chrome, Safari, Firefox and Opera.
