### ISSUE TITLE
Custom Outcome buttons on a "Start" form are not displayed in activiti-start-form component

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1706]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
Custom Outcome buttons on a "Start" form are not displayed in activiti-start-form component. I tried setting  [showOutcomeButtons]="true", however no luck! It just shows the submit button

**Expected behavior:**
Expecting the custom outcomes to be displayed on a start form

**Steps to reproduce the issue:**
My html where I noticed this issue looks like  <div>
            <activiti-start-form [processDefinitionId]="processDefinitionId"
                              [showRefreshButton]="false"
                              [showOutcomeButtons]="true"
                              (outcomeClick)="onOutcomeClick($event)">
            </activiti-start-form>
          </div>

**Component name and version:** 
ng2-activiti-form 1.2

**Browser and version:** 
Chrome

**Comment by cijujoseph** [comment]
looks like it was caching issue! Hence closing.

**Comment by cijujoseph** [comment]
Re-opening issue..It wasn't any caching issue. The issue is, I was using "Save" as the outcome on a start form. Looks like "Save" outcome is being removed on a start form as the product doesn't support OOTB save on a start form. May be this should be documented - Not to use the key word "Save" on form outcomes as it is a reserved word in the product.

**Comment by eromano** [comment]
https://github.com/Alfresco/alfresco-ng2-components/issues/1645

**Comment by DenisVuyka** [comment]
Cannot reproduce this with 1.3.0

<img width="1122" alt="screenshot 2017-04-20 13 25 31" src="https://cloud.githubusercontent.com/assets/503991/25230697/de2cf0f6-25cc-11e7-8267-1a407e7e6fe9.png">

<img width="1164" alt="screenshot 2017-04-20 13 24 20" src="https://cloud.githubusercontent.com/assets/503991/25230712/ea9881c0-25cc-11e7-9de9-38b33fe7b6ec.png">

**Comment by cijujoseph** [comment]
On a start form

**Comment by DenisVuyka** [comment]
Yes, I've made screenshots from a start form

**Comment by cijujoseph** [comment]
On a start form, the default save shouldn't be there as Activiti doesn't support "Save" on a start. It might be a regression!

**Comment by cijujoseph** [comment]
Sorry my bad, just noticed that you had two Save outcomes!

**Comment by DenisVuyka** [comment]
Yes, all the actions are custom, was just trying to test case sensitivity. The one without save/cancel works fine for me (removed and republished the app)

<img width="1180" alt="screenshot 2017-04-20 13 35 08" src="https://cloud.githubusercontent.com/assets/503991/25231078/4b8dd240-25ce-11e7-8b20-ade862eaece3.png">

I'm using current development branch, so high chance it has been fixed with some other commit.

**Comment by cijujoseph** [comment]
Strange, I still have that issue with 1.3
<img width="630" alt="screen shot 2017-04-20 at 7 39 14 am" src="https://cloud.githubusercontent.com/assets/2080360/25231222/acf5a012-259c-11e7-8681-f976835a880a.png">
<img width="477" alt="screen shot 2017-04-20 at 7 40 05 am" src="https://cloud.githubusercontent.com/assets/2080360/25231221/ace283e2-259c-11e7-975c-1b02d75fde4d.png">

**Comment by DenisVuyka** [comment]
Ok, I think it was fixed recently and will get into 1.4.0.

**Comment by cijujoseph** [comment]
I deleted the previous comment just to double check that I'm using 1.3!
Yes, 1.3 still have that issue. Might be a 1.4 fix!
<img width="630" alt="screen shot 2017-04-20 at 7 39 14 am" src="https://cloud.githubusercontent.com/assets/2080360/25231299/f6f46e96-259c-11e7-9078-b32b297bf5ab.png">
<img width="477" alt="screen shot 2017-04-20 at 7 40 05 am" src="https://cloud.githubusercontent.com/assets/2080360/25231300/f710ba06-259c-11e7-9e5a-a76f0b66c792.png">

**Comment by cijujoseph** [comment]
thanks!

**Comment by DenisVuyka** [comment]
Yes, just checked and it is in testing for 1.4.0 right now
